### ISSUE TITLE
Server Crashed

### ISSUE THREAD

**Issue by PA733** [dreamguxiang/BETweaker#1]
无征兆崩服（持续观察中）
版本：BETweaker 49号构建 
           bds 1.18.12 

`[Crashed!]
-- Unhandled Exception in -> ntdll.dll
-- Exception Code: 0xC0000374
-- Minidump generated in Directory ./logs/Crash
[TrackBack] Function RtlIsZeroMemory at 0x7FFA5FED39C0  [ntdll.dll]
[TrackBack] Function RtlIsZeroMemory at 0x7FFA5FED39C0  [ntdll.dll]
[TrackBack] Function _misaligned_access at 0x7FFA5FEDC490  [ntdll.dll]
[TrackBack] Function _misaligned_access at 0x7FFA5FEDC490  [ntdll.dll]
[TrackBack] Function _misaligned_access at 0x7FFA5FEDC490  [ntdll.dll]
[TrackBack] Function RtlGetCurrentServiceSessionId at 0x7FFA5FDEB480  [ntdll.dll]
[TrackBack] Function RtlFreeHeap at 0x7FFA5FDEB390  [ntdll.dll]
[TrackBack] Function free_base at 0x7FFA5D612070  [ucrtbase.dll]
[TrackBack] Function std::basic_string<char,std::char_traits<char>,std::allocator<char> >::~basic_string<char,std::char_traits<char>,std::allocator<char> > at 0x7FFA3F8B28C0  [BETweaker.dll]
-- At File C:\Program Files\Microsoft Visual Studio\2022\Enterprise\VC\Tools\MSVC\14.31.31103\include\xstring : Line 3007 
[TrackBack] Function ???????? at 0x????????
[TrackBack] Function _NLG_Return2 at 0x7FFA58B01150  [VCRUNTIME140_1.dll]
[TrackBack] Function _NLG_Return2 at 0x7FFA58B01150  [VCRUNTIME140_1.dll]
[TrackBack] Function _NLG_Return2 at 0x7FFA58B01150  [VCRUNTIME140_1.dll]
[TrackBack] Function _CxxFrameHandler4 at 0x7FFA58B04070  [VCRUNTIME140_1.dll]
[TrackBack] Function __GSHandlerCheck_EH4 at 0x7FFA3F8E4D18  [BETweaker.dll]
-- At File d:\a01\_work\43\s\src\vctools\crt\vcstartup\src\gs\amd64\gshandlereh4.cpp : Line 86 
[TrackBack] Function _chkstk at 0x7FFA5FE73CE0  [ntdll.dll]
[TrackBack] Function RtlUnwindEx at 0x7FFA5FDFF7A0  [ntdll.dll]
[TrackBack] Function _NLG_Return2 at 0x7FFA58B01150  [VCRUNTIME140_1.dll]
[TrackBack] Function _NLG_Return2 at 0x7FFA58B01150  [VCRUNTIME140_1.dll]
[TrackBack] Function _NLG_Return2 at 0x7FFA58B01150  [VCRUNTIME140_1.dll]
[TrackBack] Function _NLG_Return2 at 0x7FFA58B01150  [VCRUNTIME140_1.dll]
[TrackBack] Function _NLG_Return2 at 0x7FFA58B01150  [VCRUNTIME140_1.dll]
[TrackBack] Function _CxxFrameHandler4 at 0x7FFA58B04070  [VCRUNTIME140_1.dll]
[TrackBack] Function RegisterPlugin at 0x7FFA3BB509F0  [LiteLoader.dll]
[TrackBack] Function _chkstk at 0x7FFA5FE73CE0  [ntdll.dll]
[TrackBack] Function RtlVirtualUnwind2 at 0x7FFA5FE01ED0  [ntdll.dll]
[TrackBack] Function KiUserExceptionDispatcher at 0x7FFA5FE72DF0  [ntdll.dll]
[TrackBack] Function memcpy at 0x7FFA4C8D12F0  [VCRUNTIME140.dll]
[TrackBack] Function std::basic_string<char,std::char_traits<char>,std::allocator<char> >::assign at 0x7FF6759D7350  [bedrock_server_mod.exe]
[TrackBack] Function buildActorDisplayName at 0x7FF6764917F0  [bedrock_server_mod.exe]
[TrackBack] Function Helper::buildActorDisplayName at 0x7FFA3F8BB0E0  [BETweaker.dll]
-- At File D:\a\BETweaker\BETweaker\BETweaker\Main\Helper.h : Line 26 
[TrackBack] Function Helper::getActorDisplayName at 0x7FFA3F8BB260  [BETweaker.dll]
-- At File D:\a\BETweaker\BETweaker\BETweaker\Main\Helper.h : Line 34 
[TrackBack] Function <lambda_8bd32445a2bc3141fdcccb58e51179a1>::operator() at 0x7FFA3F8BB9A0  [BETweaker.dll]
-- At File D:\a\BETweaker\BETweaker\BETweaker\Kernel\HUBInfo.cpp : Line 74 
[TrackBack] Function Level::forEachPlayer at 0x7FF6767BCA50  [bedrock_server_mod.exe]
[TrackBack] Function Level::forEachPlayer at 0x7FFA3BB24FF0  [LiteLoader.dll]
[TrackBack] Function std::_Func_impl_no_alloc<<lambda_52ea8afe6475a54077f8c7500e283cdb>,void>::_Do_call at 0x7FFA3F8BEAC0  [BETweaker.dll]
-- At File C:\Program Files\Microsoft Visual Studio\2022\Enterprise\VC\Tools\MSVC\14.31.31103\include\functional : Line 834 
[TrackBack] Function Player::sendCustomFormPacket at 0x7FFA3BB33900  [LiteLoader.dll]
[TrackBack] Function TDHook_249ServerLevel_tick_86efb826::p at 0x7FFA3A984950  [trapdoor-0.10.2-1.18.12.01.dll]
-- At File C:\Users\xhy\dev\TrapDoor\mod\tick\GameTick.cpp : Line 295 
[TrackBack] Function Minecraft::update at 0x7FF676370830  [bedrock_server_mod.exe]
[TrackBack] Function ServerInstance::_update at 0x7FF675E45610  [bedrock_server_mod.exe]
[TrackBack] Function <lambda_5d63f534eeadf9e385a3ddce5663beb8>::operator() at 0x7FF675E3D5F0  [bedrock_server_mod.exe]
[TrackBack] Function std::thread::_Invoke<std::tuple<<lambda_5d63f534eeadf9e385a3ddce5663beb8> >,0> at 0x7FF675E22240  [bedrock_server_mod.exe]
[TrackBack] Function recalloc at 0x7FFA5D626AF0  [ucrtbase.dll]
[TrackBack] Function BaseThreadInitThunk at 0x7FFA5FB94EC0  [KERNEL32.DLL]
[TrackBack] Function RtlUserThreadStart at 0x7FFA5FE4E370  [ntdll.dll]`

**Comment by dreamguxiang** [comment]
代办，知道原因了
