### ISSUE TITLE
如何使用CuttingTree选项?

### ISSUE THREAD

**Issue by LittleSaya** [dreamguxiang/BETweaker#19]
Client version: 1.19.11
Server version: 1.19.10.03

好像不管我把这个选项设置成true还是false都不能一键砍树，请问我应该怎么做才能让这个设置生效？

另外我发现README的GIF里有一行`[BETweaker-Axe]快捷模式`的字样，这个和一键砍树的功能有关吗？

**Comment by dreamguxiang** [comment]
斧头下蹲右键切换模式

**Comment by LittleSaya** [comment]
> 斧头下蹲右键切换模式

谢谢，可以了，虽然按shift键左上角会出现一个小人，但还是希望能在README.md里文字说明一下
