### ISSUE TITLE
方块信息显示错误

### ISSUE THREAD

**Issue by PA733** [dreamguxiang/BETweaker#2]
紫色玻璃方块（或者，可能是任何玻璃方块）被一直显示为"Currently Harvestable"，即使玩家手上无任何物品。

**Comment by Dofes** [comment]
![QQ截图20220226234108](https://user-images.githubusercontent.com/91889957/155849262-d827cb49-d7a1-42c2-aaff-60b4549185d1.png)

**Comment by Dofes** [comment]
不能复现啊

**Comment by PA733** [comment]
能否采集不是打勾的吗
空手能采集玻璃方块吗？

**Comment by dreamguxiang** [comment]
> 能否采集不是打勾的吗 空手能采集玻璃方块吗？

在mc里玻璃就是可以采集，就是没掉落物罢了
