### ISSUE TITLE
PlayeUseItemOnEvent Error

### ISSUE THREAD

**Issue by BuslnwTH** [dreamguxiang/BETweaker#6]
crash many times BeTweaker 1.0.7 LL 2.1.7
![image](https://user-images.githubusercontent.com/17994537/163669656-63c71a6d-3c3e-4715-b76a-ee1afc7fd3bb.png)

**Comment by dreamguxiang** [comment]
Send the DMP file

**Comment by BuslnwTH** [comment]
[CrashDump_20220416_15-58-33.dmp](http://web.onmc.xyz:800/jkcbe/download/others/CrashDump_20220416_15-58-33.dmp)

**Comment by dreamguxiang** [comment]
Are there still appearances

**Comment by BuslnwTH** [comment]
no more
