### ISSUE TITLE
Crash Line 153

### ISSUE THREAD

**Issue by BuslnwTH** [dreamguxiang/BETweaker#9]
Crash after upgrade to 1.0.10 
[DMP File](http://jkcbe.onmc.xyz:800/jkcbe/download/others/CrashDump_20220430_23-23-48.dmp)

![image](https://user-images.githubusercontent.com/17994537/166114242-eabbf0ea-93ed-4f3a-abff-dc89c57c1ece.png)

**Comment by dreamguxiang** [comment]
This is not a BETweaker bug

**Comment by dreamguxiang** [comment]
This is a crash caused by thorns pvp(MCBUG)
You can install llac to fix it.
